### ISSUE TITLE
))

### ISSUE THREAD

**Issue by mamura123** [Stealerium/Stealerium#110]
<img width="1067" alt="image_2023-04-08_01-47-30" src="https://user-images.githubusercontent.com/122900148/230689857-dc159111-c7a5-4f96-9987-590e2151c95f.png">

:)

**Comment by mamura123** [comment]
![Uploading image_2023-04-08_17-55-43.png…]()

**Comment by mamura123** [comment]
<img width="826" alt="image_2023-04-08_17-55-43" src="https://user-images.githubusercontent.com/122900148/230728171-ca95b6a0-d5e4-4090-8ae9-4ed867ae8654.png">

**Comment by kgnfth** [comment]
Nice job!
