### ISSUE TITLE
files aren't getting uploaded to anonfiles.

### ISSUE THREAD

**Issue by issuemakers** [Stealerium/Stealerium#20]
files aren't getting uploaded to anonfiles, it's the second time it does this. Maybe it's too big but i think maybe it's because of some countries/vpn you cannot access anonfiles. Can you please provide a fix

![Untitled](https://user-images.githubusercontent.com/106458395/170849876-84bfaf52-209c-4bc6-b0ea-c2590a37cc0f.png)

**Comment by kgnfth** [comment]
Yes, that is a known issue, i am looking for a alternative file storage provider
if u know some, you can always leave a comment

**Comment by allahjum** [comment]
https://filetransfer.io/

**Comment by allahjum** [comment]
https://easyupload.io/
https://uploadcare.com/products/file-uploader/
https://www.file.io/
https://fastupload.io/

**Comment by kgnfth** [comment]
Merhaba, i decided to go with https://gofile.io

**Comment by allahjum** [comment]
> Merhaba, i decided to go with https://gofile.io

I like it
when can you release it?

**Comment by kgnfth** [comment]
Could you guys try the new release https://github.com/Stealerium/Stealerium/releases/tag/Build_2022.06.01_19-27
