### ISSUE TITLE
Doesn't send anything to webhook after executed...

### ISSUE THREAD

**Issue by XMVZ** [Stealerium/Stealerium#3]
Executed build.. On 5 machines. Nothing is sent.. Maybe it went to you...?

![image](https://user-images.githubusercontent.com/79497004/166851919-c0500eb9-b9bd-4dad-ba18-7edb19d9630b.png)

**Comment by 13Zorawar** [comment]
same problem its almost 12 and i dont get any update
any fix?

**Comment by kgnfth** [comment]
> Executed build.. On 5 machines. Nothing is sent.. Maybe it went to you...?
> 
> ![image](https://user-images.githubusercontent.com/79497004/166851919-c0500eb9-b9bd-4dad-ba18-7edb19d9630b.png)

I did not put any hidden webhook to my discord, the source is open you can see it yourself.
Sometimes it wont work because it gets dedected by AV

did u test it on a virtual machine?
