### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by lexxxxxxx7** [Stealerium/Stealerium#36]
I keep getting this error, am I supposed to change the file path?
![image](https://user-images.githubusercontent.com/103804488/173005978-cb580dc2-f011-4dd1-a5f2-5dedca84daf7.png)

**Comment by kgnfth** [comment]
What are u trying to do ?

**Comment by lexxxxxxx7** [comment]
I ran the builder in visual studio but that error kept coming up. I deleted it and downloaded the whole thing again and ran the stub first this time and it kept saying that
![image](https://user-images.githubusercontent.com/103804488/173176695-63704fc5-f3d2-4427-ab3b-4fc0e973afb8.png)
What am I doing wrong? How do I build the stub? I apologise if these questions sound stupid, I code in other languages and visual studio is a new application for me.

**Comment by kgnfth** [comment]
> I ran the builder in visual studio but that error kept coming up. I deleted it and downloaded the whole thing again and ran the stub first this time and it kept saying that ![image](https://user-images.githubusercontent.com/103804488/173176695-63704fc5-f3d2-4427-ab3b-4fc0e973afb8.png) What am I doing wrong? How do I build the stub? I apologise if these questions sound stupid, I code in other languages and visual studio is a new application for me.

Just right click the Solution and build click build solution

**Comment by lexxxxxxx7** [comment]
sorry its still not working

**Comment by kgnfth** [comment]
You cant debug the Builder unless you change the path to the Stub, or move the stub.exe to the path shown in the error screen.

**Comment by lexxxxxxx7** [comment]
whats the manual way to do it without the builder?

**Comment by kgnfth** [comment]
get the prebuilt from https://github.com/Stealerium/Stealerium/releases
