### ISSUE TITLE
Doesn't work startup and capture of web camera

### ISSUE THREAD

**Issue by Uns0lved** [Stealerium/Stealerium#40]
Problem 1:
I create bild with function "startup", but module "startup" doesn't work. I checked SC of this project and find way to "autostartup", 
![изображение](https://user-images.githubusercontent.com/55342617/174083747-8f49db78-0362-4800-8e06-b1426d4e31d9.png)
but when i open this folder and i doesn't find this file
![изображение](https://user-images.githubusercontent.com/55342617/174084355-db0475c5-a2db-49bc-88a6-6c4169b734b2.png)
other way:
![изображение](https://user-images.githubusercontent.com/55342617/174084413-003416bb-23bc-4431-b76e-a8e996272291.png)

Problem 2:
I have laptop with web camera, when i opened this stealer, indicator of web camera is turned on, in discord it send information about capture of web camera
![изображение](https://user-images.githubusercontent.com/55342617/174085474-029f1615-276e-4aa2-990f-74ed7be17ec8.png)
but in archive i doesn't find any capture of web camera

**Comment by Uns0lved** [comment]
> Thx for the report, as i have no time to fix, i try to work on this project when i have time
> 
> For the camera, can u run it again but build again with option Debug mode then run that file after that send the log file here, whch is located at `C:\Users\fatih\AppData\Local\Temp\Stealerium-Latest.log` or in the final archive file in `System\\Debug.txt`
> 
> it does not contain any personal information, you can remove the pc name and other info if u are paranoia 😊

In debug logs i don't see any code with web camera, but i see that this stealer couldn't recover data in firefox
![изображение](https://user-images.githubusercontent.com/55342617/174106231-a5e4af2b-141f-45f9-a78a-9e4428e30526.png)

[Debug.txt](https://github.com/Stealerium/Stealerium/files/8920266/Debug.txt)

**Comment by kgnfth** [comment]
Hmm it should report `webcamScreenshot : Camera screenshot failed` if failed

**Comment by Uns0lved** [comment]
> bcamScreenshot : C

Bro, I fixed startup XD. I can give you SC with fixed startup in discord. If you want know "how i fix it?", I wait you at discord.
But i don't fix camera.


![изображение](https://user-images.githubusercontent.com/55342617/174134773-55259704-8596-49af-bd40-2b32168bad40.png)

**Comment by Uns0lved** [comment]
> Hmm it should report `webcamScreenshot : Camera screenshot failed` if failed

Video proof) https://youtu.be/X6FXWKyKLqo

**Comment by Uns0lved** [comment]
> Thx for the fix, you can send a pull request if u want i dont have a webcam to test it, so i need to figure out on how to create a fake camera

idk how create pull request, maybe i give you archive with sc? About webcam: you can download plugin for OBS from official site(https://obsproject.com/forum/resources/obs-virtualcam.539/) and restart obs, then you can click to Instruments(T) - virtual cam, and press start
![изображение](https://user-images.githubusercontent.com/55342617/174146244-9e557ae5-2374-41dc-808b-dada19662488.png)
![изображение](https://user-images.githubusercontent.com/55342617/174146317-ae6ae423-05c9-41f7-b8fe-33fa62197893.png)

**Comment by ledoanhung** [comment]
> e i give you archive with sc? About webcam: you can download plugin for OBS from official site(https://obsproject.com/forum/resources/obs-virtualcam.539/) and restart obs, then you can click to Instruments(T) - virtual cam, and press start

can you help me brp

**Comment by ledoanhung** [comment]
> Bro, I fixed startup XD. I can give you SC with fixed startup in discord. If you want know "how i fix it?", I wait you at discord. But i don't fix camera. DC: 1520#8492
> 
> ![изображение](https://user-images.githubusercontent.com/55342617/174134773-55259704-8596-49af-bd40-2b32168bad40.png)
> 
> > Hmm it should report `webcamScreenshot : Camera screenshot failed` if failed

give SC fixed pls bro
