### ISSUE TITLE
Crypto Wallets

### ISSUE THREAD

**Issue by PandoricGalaxy** [Stealerium/Stealerium#6]
Crypto wallet files are grabbed but how do i use them to access the wallet? There is no recovery phase in those files

**Comment by kgnfth** [comment]
@PandoricGalaxy Help like this will not be provided.

**Comment by PandoricGalaxy** [comment]
> @PandoricGalaxy Help like this will not be provided.

Why? What's wrong in asking it? I just wanna know how can the file be decrypted
