### ISSUE TITLE
Stub folder gone!

### ISSUE THREAD

**Issue by Swecrypto5** [Stealerium/Stealerium#60]
Hey first of all! awesome work with the Stealerium!
I did manage to try it out on my self and it worked perfectly awesome!
But after that the stub folder is gone? And i assume that it is the Stubconfig.exe hat is the stealer?
Does it beeing automatically downloaded to a PC if its put in a link or how does it work particallury?
![image](https://user-images.githubusercontent.com/105457944/184000956-2ee4a526-f478-4861-afc4-714123dac61d.png)

Keep up the good work!

**Comment by kgnfth** [comment]
Thanks. read the code, trust me you will understand it.
