### ISSUE TITLE
I get an error when i try to build an .exe file

### ISSUE THREAD

**Issue by peebeekay** [Stealerium/Stealerium#7]
Can you PLEASE help me out? I don;t know what i am doing wrong. I am a beginner at best and trying to learn as I go but i can't figure out why it wont let me build a .exe file. Any help would be GREATLY appreacited!! Thank you!!! 

![stealer](https://user-images.githubusercontent.com/73264592/167836542-937e35dc-5407-4e2f-b186-d1f25e3df639.PNG)

**Comment by kgnfth** [comment]
If u read the error log you will understand why it won't build,
it can't find the file stub.exe in this path `C:\Users\whati\Desktop\Stealerium\Stub`

The stub.exe is needed the for the build.

Don't delete the file or if u did not deleted it, turn of your antivirus temporarily.
